djp/mysite/mysite/home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

djp/mysite/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^$/', include('home.urls', namespace="home")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

djp/mysite/mysite/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

# routing url

# Browser richiede pagina, il routing url la trova (regexp) (oppure 404)
# models.py (modello) definisce gli oggetti e la relazione col database
# la view riceve richieste dal routing e invia altre richieste, templetizzate o meno
# (vedere index e details templetizzati), passando eventuali parametri (in index gestisco un get di ordinamento)

djp/mysite/mysite/home/models.py
from django.db import models

# Create your models here.

djp/mysite/mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Data pubblicazione')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Pubblicato recentemente?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

djp/mysite/mysite/home/views.py
from django.http import HttpResponse

def index(request):
    return HttpResponse("Home!")

djp/mysite/mysite/polls/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render, get_object_or_404

from .models import Question

def index(request):
    # Inventiamo
    # Ordinamento ASC/DESC SQL a seconda del parametro get 'ord'
    # e re-inviato a dettagli.html come 'ordinamento'
    ord = request.GET.get('ord')
    query = 'pub_date'
    if ord == "asc":
        query = "-pub_date"
    latest_question_list = Question.objects.order_by(query)[:5]
    parametri = {
        'latest_question_list': latest_question_list,
        'ordinamento': ord
    }
    return render(request, 'polls/index.html', parametri)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    # Creazione indici domanda precedente/successiva
    prec = int(question_id) - 1;
    succ = int(question_id) + 1;

    if not Question.objects.filter(pk=prec).exists():
        prec = None

    if not Question.objects.filter(pk=succ).exists():
        succ = None

    parametri = {
        'question': question,
        'prec': prec, # precedente
        'succ': succ, # Successivo
    }
    return render(request, 'polls/dettagli.html', parametri)

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

djp/mysite/mysite/polls/templates/polls/dettagli.html
<center>
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<br>
<input type="submit" value="Vote" />
</form>

<br/>

{% if prec %}
    <a href="{% url 'polls:detail' prec %}" title="Precedente"> <<-- </a>
{% endif %}

    <a href="{% url 'polls:index' %}" title="Lista">Lista</a>

{% if succ %}
    <a href="{% url 'polls:detail' succ %}" title="Precedente"> -->> </a>
{% endif %}
</center>

djp/mysite/mysite/polls/templates/polls/index.html
<center>
    <h1> Domande </h2>
{% if latest_question_list %}
    {% for question in latest_question_list %}
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a><br/>
    {% endfor %}
    <br/>
    {% if ordinamento == "asc" %}
        <a href="{% url 'polls:index' %}?ord=desc" title="Ordina DESC">Ordina -> </a>
    {% else %}
        <a href="{% url 'polls:index' %}?ord=asc" title="Ordina ASC">Ordina <- </a>
    {% endif %}
{% else %}
    <p>Nessuna domanda trovata.</p>
{% endif %}

</center>